### ISSUE TITLE
power-off feature

### ISSUE THREAD

**Issue by mrmrmrmr1** [unknownskl/xbox-smartglass-core-node#4]
will there be a power-off feature as well ?

**Comment by unknownskl** [comment]
Working on this at the moment. The crypto connection to the xbox one is quite hard to do in NodeJS. 
The Python implementation supports it already (https://github.com/OpenXbox/xbox-smartglass-core-python)

**Comment by mrmrmrmr1** [comment]
I see. Thanks for your answer. I tried to figure it out from Python code and do the nodejs myself but I am not that good in coding. I didn't even understand the Python code. waiting for your good news.

**Comment by mrmrmrmr1** [comment]
Do you have any updates about power-off feature ?
I'd be more than happy if I could help.

**Comment by unknownskl** [comment]
Right now nothing yet, still working on the implementation. It is very hard to debug as the console would not say back what is going wrong.
The implementation could take weeks or months to be implemented, right now I am stuck. 

If you want to have a chat about this, you can find me in the discord server of OpenXbox.

**Comment by mrmrmrmr1** [comment]
well, I don't have much to add. I don't know what discord server is though I guess it is a communication method. But I can't find anything like "discord server openxbox"
Anyway, where are you stuck at ?  if you understand Python, isn't it easier to port ?

**Comment by unknownskl** [comment]
You can find the link to the discord server at the bottom of their homepage: https://openxbox.org/

I am currently stuck at deriving the shared secret from the certificate. I am planning to do an more intensive dive in to the crypto part (using the python version next to it and comparing the values), but currently my time doesn't allow it. Hopefully the coming weekend i have some time to dive in.

**Comment by unknownskl** [comment]
The power on function is a bit unstable at the moment of writing. I will look into this after I got the authentication working.

I got the authentication kind of working by using python to derive the key. It is coming closer. For now the next steps are:
- Make a permanent solution for the authentication (embed python inside nodejs / use the bitcoin secp256r1 library to derive the secret)
- Create library to encrypt and sign the messages to the Xbox. (For now only to turn off the Xbox)

I only have some limited time to work on this so once it is there I will update the library. (Only have +- 1 day in the week to work on this, sadly.)

**Comment by mrmrmrmr1** [comment]
good to learn that you have progress.
please let me know if you need any help (test or other) from an amateur coder who has zero knowledge on python/nodejs

**Comment by mrmrmrmr1** [comment]
do you have any progress on release ? 
thx.

**Comment by mrmrmrmr1** [comment]
hi,
do you have any updates ?

**Comment by unknownskl** [comment]
Hello there, 

Unfortunately not. At this moment I've put the project on hold till there is more time to develop this.

Maybe the smartglass rest server can help you? https://github.com/OpenXbox/xbox-smartglass-rest-python

**Comment by mrmrmrmr1** [comment]
I want to control Xbox through my Smartthings platform. That requires a nodejs interface. Can't make it through python. 
Last time you'd told that you were very close to an update. What prevented you ? is there a blocking point ?

**Comment by mrmrmrmr1** [comment]
now checked and seems like I can use a rest server. but I could not find the list of endpoints supported. is there something to power off ?

**Comment by unknownskl** [comment]
In the file xbox/rest/routes/device.py (https://github.com/OpenXbox/xbox-smartglass-rest-python/blob/master/xbox/rest/routes/device.py) you can find the power off function. 

I don't have the smartthings platform at home so I cannot really help you. However, it is possible to create a nodejs library that interacts with the rest server.

**Comment by mrmrmrmr1** [comment]
thanks. I installed it and it really works. now I am working on a smartthings device handler to send the rest commands for "power on" and "power off"

**Comment by mrmrmrmr1** [comment]
ok. finally , the rest server is integrated with my smartthings platform.
it works fine. thanks for your suggestion.

**Comment by unknownskl** [comment]
Great to hear that! It's the script open source by any chance? Might be worth to share it for others :-)

**Comment by mrmrmrmr1** [comment]
actually I just added 2 commands (on & off) to a presence device handler which already shows the state of the Xbox (by pinger) 
So , the additional script is below:

```
def on() {
    def host = "192.168.254.199" 
    def port = "5557"
    def hosthex = convertIPtoHex(host).toUpperCase() //thanks to @foxxyben for catching this
    def porthex = convertPortToHex("5557").toUpperCase()    
    def path = "/device/$liveid/poweron"
    def headers = [:] 
    headers.put("HOST", "$host:$port")
    def method = "GET"
    
    try {
    def hubAction = new physicalgraph.device.HubAction(
    	method: method,
    	path: path,
    	headers: headers
        )
        sendHubCommand(hubAction)
    }
    catch (Exception e) {
    	log.debug "Hit Exception $e on $hubAction"
    }
}

def off() {
	return [conn(), delayAction(10000), powerof()]
}

def powerof() {
    def host = "192.168.254.199" 
    def port = "5557"
    def hosthex = convertIPtoHex(host).toUpperCase() //thanks to @foxxyben for catching this
    def porthex = convertPortToHex("5557").toUpperCase()
    def path = "/device/$liveid/poweroff"
    def headers = [:] 
    headers.put("HOST", "$host:$port")
    def method = "GET"
    
    try {
    def hubAction = new physicalgraph.device.HubAction(
    	method: method,
    	path: path,
    	headers: headers
        )
        sendHubCommand(hubAction)
    }
    catch (Exception e) {
    	log.debug "Hit Exception $e on $hubAction"
    }
}

def conn() {
    def host = "192.168.254.199" 
    def port = "5557"
    def hosthex = convertIPtoHex(host).toUpperCase() //thanks to @foxxyben for catching this
    def porthex = convertPortToHex("5557").toUpperCase() 
    def path = "/device/$liveid/connect"
    def headers = [:] 
    headers.put("HOST", "$host:$port")
    def method = "GET"
    
    try {
    def hubAction = new physicalgraph.device.HubAction(
    	method: method,
    	path: path,
    	headers: headers
        )
        sendHubCommand(hubAction)
    }
    catch (Exception e) {
    	log.debug "Hit Exception $e on $hubAction"
    }
}


private String convertIPtoHex(ipAddress) { 
    String hex = ipAddress.tokenize( '.' ).collect {  String.format( '%02x', it.toInteger() ) }.join()
    return hex
}

private String convertPortToHex(port) {
	String hexport = port.toString().format( '%04x', port.toInteger() )
    return hexport
}

def parse(String description) {
    log.debug "Parsing '${description}'"
}

private delayAction(long time) {
	new physicalgraph.device.HubAction("delay $time")
}
```

it basically calls poweron , connect and poweroff endpoints of the rest server.
LiveID is given as an attribute to the device. My rest server IP address (192.168.254.199) is static in the code. User should change it according to his/her environment.

**Comment by unknownskl** [comment]
Power off functionality has been implemented. See docs.
